// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tracker.proto

/*
Package anomalytracker is a generated protocol buffer package.

It is generated from these files:
	tracker.proto

It has these top-level messages:
	Anomaly
*/
package anomalytracker

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Anomaly struct {
	Id               *string `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	System           *string `protobuf:"bytes,2,req,name=system" json:"system,omitempty"`
	Type             *string `protobuf:"bytes,3,req,name=type" json:"type,omitempty"`
	Name             *string `protobuf:"bytes,4,req,name=name" json:"name,omitempty"`
	InternalId       *int64  `protobuf:"varint,5,req,name=internal_id,json=internalId" json:"internal_id,omitempty"`
	UserId           *int64  `protobuf:"varint,6,req,name=user_id,json=userId" json:"user_id,omitempty"`
	GroupId          *int64  `protobuf:"varint,7,req,name=group_id,json=groupId" json:"group_id,omitempty"`
	Created          *string `protobuf:"bytes,8,req,name=created" json:"created,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Anomaly) Reset()                    { *m = Anomaly{} }
func (m *Anomaly) String() string            { return proto.CompactTextString(m) }
func (*Anomaly) ProtoMessage()               {}
func (*Anomaly) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Anomaly) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *Anomaly) GetSystem() string {
	if m != nil && m.System != nil {
		return *m.System
	}
	return ""
}

func (m *Anomaly) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *Anomaly) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Anomaly) GetInternalId() int64 {
	if m != nil && m.InternalId != nil {
		return *m.InternalId
	}
	return 0
}

func (m *Anomaly) GetUserId() int64 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *Anomaly) GetGroupId() int64 {
	if m != nil && m.GroupId != nil {
		return *m.GroupId
	}
	return 0
}

func (m *Anomaly) GetCreated() string {
	if m != nil && m.Created != nil {
		return *m.Created
	}
	return ""
}

func init() {
	proto.RegisterType((*Anomaly)(nil), "anomalytracker.Anomaly")
}

func init() { proto.RegisterFile("tracker.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 182 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0xcd, 0xb1, 0x0e, 0x82, 0x30,
	0x10, 0xc6, 0xf1, 0x50, 0x90, 0xe2, 0x19, 0x19, 0x6e, 0xd0, 0x3a, 0x49, 0x9c, 0x98, 0x7c, 0x07,
	0x47, 0x56, 0x5e, 0xc0, 0x34, 0xf4, 0x62, 0x1a, 0xa1, 0x25, 0xa5, 0x0c, 0xbc, 0xa1, 0x8f, 0x65,
	0x5a, 0x60, 0xbb, 0xef, 0xf7, 0x1f, 0x0e, 0xce, 0xde, 0xc9, 0xee, 0x4b, 0xee, 0x39, 0x3a, 0xeb,
	0x2d, 0x96, 0xd2, 0xd8, 0x41, 0xf6, 0xcb, 0xa6, 0x8f, 0x5f, 0x02, 0xfc, 0xb5, 0x12, 0x96, 0xc0,
	0xb4, 0x12, 0x49, 0xc5, 0xea, 0x63, 0xcb, 0xb4, 0xc2, 0x0b, 0xe4, 0xd3, 0x32, 0x79, 0x1a, 0x04,
	0x8b, 0xb6, 0x2d, 0x44, 0xc8, 0xfc, 0x32, 0x92, 0x48, 0xa3, 0xc6, 0x3b, 0x98, 0x91, 0x03, 0x89,
	0x6c, 0xb5, 0x70, 0xe3, 0x1d, 0x4e, 0xda, 0x78, 0x72, 0x46, 0xf6, 0x6f, 0xad, 0xc4, 0xa1, 0x62,
	0x75, 0xda, 0xc2, 0x4e, 0x8d, 0xc2, 0x2b, 0xf0, 0x79, 0x22, 0x17, 0x62, 0x1e, 0x63, 0x1e, 0x66,
	0xa3, 0xf0, 0x06, 0xc5, 0xc7, 0xd9, 0x79, 0x0c, 0x85, 0xc7, 0xc2, 0xe3, 0x6e, 0x14, 0x0a, 0xe0,
	0x9d, 0x23, 0xe9, 0x49, 0x89, 0x22, 0xfe, 0xda, 0xe7, 0x3f, 0x00, 0x00, 0xff, 0xff, 0x92, 0x10,
	0x0f, 0xe1, 0xea, 0x00, 0x00, 0x00,
}
